### ISSUE TITLE
Error when trying to install the package

### ISSUE THREAD

**Issue by m3du** [deruncie/PLS205_package#1]
Error: Failed to install 'PLS205' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘ps’

R version 4.0.2 (2020-06-22)
Rstudio Version 1.3.1073

**Comment by deruncie** [comment]
are you on a mac or pc?

**Comment by deruncie** [comment]
Try this: https://gitmemory.com/issue/valentinitnelav/bootstrapnet/24/679197289

**Comment by m3du** [comment]
I am on pc. I manually installed each package and it worked. Thank you for the link as well!
